# Generated by Django 3.2 on 2022-07-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='p_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
