# Generated by Django 3.2.15 on 2023-01-09 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20220920_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField( upload_to='static/img/categorias'),
            preserve_default=False,
        ),
    ]
