# Generated by Django 3.2.15 on 2023-01-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_categoria_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
